### ISSUE TITLE
Unable to run the build script

### ISSUE THREAD

**Issue by roman87** [TeamMentor/TM_4_0_Design#108]
I am unable to run the build script as specified here in step 6
https://github.com/TeamMentor/TM_4_0_Design/wiki/How-to-build-and-run-the-QA-unit-tests

I get this:
rom@TITI08:~/Dev/TeamMentor/TM_4_0_Design/build$ npm run build

> TM-4.0-Design_Build@0.5.0 build /home/rom/Dev/TeamMentor/TM_4_0_Design/build
> node ./node_modules/mocha/bin/mocha --compilers coffee:coffee-script/register -R list build_TM_4_0_Design.coffee

  ․ build TM_4_0_Design | Clean target folders: 70ms
  ․ build TM_4_0_Design | Compile scss files: 12ms
  ․ build TM_4_0_Design | Compile Jade files: 35ms
  ․ build TM_4_0_Design | Compile Coffee files: 280ms
  ․ build TM_4_0_Design | Copy assets: 114ms
  1) build TM_4_0_Design | Confirm files compiled/copied ok

  5 passing (520ms)
  1 failing

  1) build TM_4_0_Design | Confirm files compiled/copied ok:
     AssertionError: [assert_Size_Is_Bigger_Than] expected bigger than 3, but it was 0 
    at Boolean.assert_Is_True (/home/rom/Dev/TeamMentor/TM_4_0_Design/build/node_modules/fluentnode/src/fluent-assert.coffee:43:50)
    at Array.assert_Size_Is_Bigger_Than (/home/rom/Dev/TeamMentor/TM_4_0_Design/build/node_modules/fluentnode/src/fluent-assert.coffee:33:61)
    at Context.<anonymous> (/home/rom/Dev/TeamMentor/TM_4_0_Design/build/build_TM_4_0_Design.coffee:64:47)
    at Test.Runnable.run (/home/rom/Dev/TeamMentor/TM_4_0_Design/build/node_modules/mocha/lib/runnable.js:217:15)
    at Runner.runTest (/home/rom/Dev/TeamMentor/TM_4_0_Design/build/node_modules/mocha/lib/runner.js:373:10)
    at /home/rom/Dev/TeamMentor/TM_4_0_Design/build/node_modules/mocha/lib/runner.js:451:12
    at next (/home/rom/Dev/TeamMentor/TM_4_0_Design/build/node_modules/mocha/lib/runner.js:298:14)
    at /home/rom/Dev/TeamMentor/TM_4_0_Design/build/node_modules/mocha/lib/runner.js:308:7
    at next (/home/rom/Dev/TeamMentor/TM_4_0_Design/build/node_modules/mocha/lib/runner.js:246:23)
    at Object._onImmediate (/home/rom/Dev/TeamMentor/TM_4_0_Design/build/node_modules/mocha/lib/runner.js:275:5)
    at processImmediate [as _immediateCallback] (timers.js:345:15)
  

npm ERR! TM-4.0-Design_Build@0.5.0 build: `node ./node_modules/mocha/bin/mocha --compilers coffee:coffee-script/register -R list build_TM_4_0_Design.coffee`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the TM-4.0-Design_Build@0.5.0 build script.
npm ERR! This is most likely a problem with the TM-4.0-Design_Build package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node ./node_modules/mocha/bin/mocha --compilers coffee:coffee-script/register -R list build_TM_4_0_Design.coffee
npm ERR! You can get their info via:
npm ERR!     npm owner ls TM-4.0-Design_Build
npm ERR! There is likely additional logging output above.
npm ERR! System Linux 3.16-0.bpo.2-amd64
npm ERR! command "/usr/local/bin/node" "/usr/local/bin/npm" "run" "build"
npm ERR! cwd /home/rom/Dev/TeamMentor/TM_4_0_Design/build
npm ERR! node -v v0.10.33
npm ERR! npm -v 1.4.28
npm ERR! code ELIFECYCLE
npm ERR! 
npm ERR! Additional logging details can be found in:
npm ERR!     /home/rom/Dev/TeamMentor/TM_4_0_Design/build/npm-debug.log
npm ERR! not ok code 0

**Comment by romichg** [comment]
This is fixed.
