### ISSUE TITLE
Error in TM_4_0_GraphDB : cannot call next() after end()

### ISSUE THREAD

**Issue by michaelhidalgo** [TeamMentor/TM_4_0_Design#219]
I'm updating my local branches and when I try to run TM 4.0 and fetch some articles, 

I got this error 

Error: cannot call next() after end()
  at ReadStream.read [as _read] (/Users/michaelhidalgo/TM4.0/TM_4_0_GraphDB/node_modules/levelgraph/node_modules/levelup/lib/read-stream.js:49:18)
  at ReadStream.Readable.read (/Users/michaelhidalgo/TM4.0/TM_4_0_GraphDB/node_modules/levelgraph/node_modules/readable-stream/lib/_stream_readable.js:362:10)
  at ReadStream.<anonymous> (/Users/michaelhidalgo/TM4.0/TM_4_0_GraphDB/node_modules/levelgraph/node_modules/readable-stream/lib/_stream_readable.js:785:45)
  at ReadStream.EventEmitter.emit (events.js:92:17)
  at emitReadable_ (/Users/michaelhidalgo/TM4.0/TM_4_0_GraphDB/node_modules/levelgraph/node_modules/readable-stream/lib/_stream_readable.js:448:10)
  at emitReadable (/Users/michaelhidalgo/TM4.0/TM_4_0_GraphDB/node_modules/levelgraph/node_modules/readable-stream/lib/_stream_readable.js:444:5)
  at readableAddChunk (/Users/michaelhidalgo/TM4.0/TM_4_0_GraphDB/node_modules/levelgraph/node_modules/readable-stream/lib/_stream_readable.js:187:9)
  at ReadStream.Readable.push (/Users/michaelhidalgo/TM4.0/TM_4_0_GraphDB/node_modules/levelgraph/node_modules/readable-stream/lib/_stream_readable.js:149:10)
  at /Users/michaelhidalgo/TM4.0/TM_4_0_GraphDB/node_modules/levelgraph/node_modules/levelup/lib/read-stream.js:63:12

npm ERR! TM_4_0_GraphDB@0.0.1 start: `node index.js`
npm ERR! Exit status 8
npm ERR! 
npm ERR! Failed at the TM_4_0_GraphDB@0.0.1 start script.
npm ERR! This is most likely a problem with the TM_4_0_GraphDB package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node index.js
npm ERR! You can get their info via:
npm ERR!     npm owner ls TM_4_0_GraphDB
npm ERR! There is likely additional logging output above.
npm ERR! System Darwin 14.0.0
npm ERR! command "node" "/usr/local/bin/npm" "start"
npm ERR! cwd /Users/michaelhidalgo/TM4.0/TM_4_0_GraphDB
npm ERR! node -v v0.10.28
npm ERR! npm -v 1.4.9
npm ERR! code ELIFECYCLE
npm ERR! 
npm ERR! Additional logging details can be found in:
npm ERR!     /Users/michaelhidalgo/TM4.0/TM_4_0_GraphDB/npm-debug.log
npm ERR! not ok code 0

This is the current file structure for the Graph 
![screen shot 2015-01-08 at 9 55 38 am](https://cloud.githubusercontent.com/assets/1732035/5665328/5671b6dc-971d-11e4-9035-b9606fa213c4.png)

**Comment by michaelhidalgo** [comment]
It turns out that the  .tm-Config file was missing

https://github.com/TeamMentor/TM_4_0_Design/wiki/Troubleshooting-running-QA-scripts

**Comment by roman87** [comment]
I am having exact same issue. And I do have my .tm-Config :)

**Comment by roman87** [comment]
Mine happens pretty much every time i try to go to navigate somewhere:
Server started at: http://localhost:1332

events.js:72
        throw er; // Unhandled 'error' event
              ^
Error: cannot call next() after end()
  at ReadStream.read [as _read] (/home/rom/Dev/TeamMentor/TM_4_0_GraphDB/node_modules/levelgraph/node_modules/levelup/lib/read-stream.js:49:18)
  at ReadStream.Readable.read (/home/rom/Dev/TeamMentor/TM_4_0_GraphDB/node_modules/levelgraph/node_modules/readable-stream/lib/_stream_readable.js:362:10)
  at ReadStream.<anonymous> (/home/rom/Dev/TeamMentor/TM_4_0_GraphDB/node_modules/levelgraph/node_modules/readable-stream/lib/_stream_readable.js:785:45)
  at ReadStream.emit (events.js:92:17)
  at emitReadable_ (/home/rom/Dev/TeamMentor/TM_4_0_GraphDB/node_modules/levelgraph/node_modules/readable-stream/lib/_stream_readable.js:448:10)
  at emitReadable (/home/rom/Dev/TeamMentor/TM_4_0_GraphDB/node_modules/levelgraph/node_modules/readable-stream/lib/_stream_readable.js:444:5)
  at readableAddChunk (/home/rom/Dev/TeamMentor/TM_4_0_GraphDB/node_modules/levelgraph/node_modules/readable-stream/lib/_stream_readable.js:187:9)
  at ReadStream.Readable.push (/home/rom/Dev/TeamMentor/TM_4_0_GraphDB/node_modules/levelgraph/node_modules/readable-stream/lib/_stream_readable.js:149:10)
  at /home/rom/Dev/TeamMentor/TM_4_0_GraphDB/node_modules/levelgraph/node_modules/levelup/lib/read-stream.js:63:12


npm ERR! TM_4_0_GraphDB@0.0.1 start: `node index.js`
npm ERR! Exit status 8
npm ERR! 
npm ERR! Failed at the TM_4_0_GraphDB@0.0.1 start script.
npm ERR! This is most likely a problem with the TM_4_0_GraphDB package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node index.js
npm ERR! You can get their info via:
npm ERR!     npm owner ls TM_4_0_GraphDB
npm ERR! There is likely additional logging output above.
npm ERR! System Linux 3.16-0.bpo.2-amd64
npm ERR! command "/usr/local/bin/node" "/usr/local/bin/npm" "start"
npm ERR! cwd /home/rom/Dev/TeamMentor/TM_4_0_GraphDB
npm ERR! node -v v0.10.33
npm ERR! npm -v 1.4.28
npm ERR! code ELIFECYCLE
npm ERR! 
npm ERR! Additional logging details can be found in:
npm ERR!     /home/rom/Dev/TeamMentor/TM_4_0_GraphDB/npm-debug.log
npm ERR! not ok code 0
rom@TITI08:~/Dev/TeamMentor/TM_4_0_GraphDB$ 
rom@TITI08:~/Dev/TeamMentor/TM_4_0_GraphDB$ 
rom@TITI08:~/Dev/TeamMentor/TM_4_0_GraphDB$ 
rom@TITI08:~/Dev/TeamMentor/TM_4_0_GraphDB$ ls
bin  db-queries  node_modules   package.json  src   test_move_to_ci
db   index.js    npm-debug.log  README.md     test  views
rom@TITI08:~/Dev/TeamMentor/TM_4_0_GraphDB$ cat .tm-Config.json 
{
  "tm_User": {
                "username": "tm_userName",
                "token": "aaca2360-34ab-4fbb-bf21-992c87eed7e1"
             }
}
rom@TITI08:~/Dev/TeamMentor/TM_4_0_GraphDB$ 
rom@TITI08:~/Dev/TeamMentor/TM_4_0_GraphDB$

**Comment by roman87** [comment]
And when things do work, I get no results..
![selection_041](https://cloud.githubusercontent.com/assets/1326120/5667328/e0adce6e-9734-11e4-82d4-3bf5c7ee41cf.png)

**Comment by DinisCruz** [comment]
try removing the GraphDB .tmCache folder and reloading the tm-uno data https://github.com/TeamMentor/TM_4_0_Design/wiki/How-to-build-and-run-the-GraphDB

**Comment by DinisCruz** [comment]
also make sure that all is up-to-date by running the ```git submodule update``` and  ```npm install```

**Comment by DinisCruz** [comment]
and check that the user defined in the auth token exists on the target 3.5 instance

**Comment by roman87** [comment]
So this looks like this was a result of the database not being able to authenticate to 3.5 back end, yet still trying to download the data. On the backend, Somehow, the user I was using had disappeared. The file for the user was there, yet it was 0kb in size. 
I updated the wiki with instructions on how to create a new user and a new auth token. 
https://github.com/TeamMentor/TM_4_0_Design/wiki/How-to-build-and-run-the-GraphDB

Also opened two new issues #220 and #221  which relate to this issue.
