### ISSUE TITLE
2 tests fail in windows, but not in linux

### ISSUE THREAD

**Issue by roman87** [TeamMentor/TM_4_0_Design#420]
```
 161 passing (28s)
 2 pending
 2 failing

 1) test-Server | start and stop:
    Error: timeout of 2000ms exceeded
   at [object Object].<anonymous> (c:\TeamMentor\TMDEVRO-Site_beta.teammentor.n
t\TM40\TM_4_0_GraphDB\node_modules\mocha\lib\runnable.js:159:19)
   at Timer.listOnTimeout [as ontimeout] (timers.js:112:15)


 2) | services | Content-Service.test | library_Folder:
    AssertionError: expected string 'c:\TeamMentor\TMDEVRO-Site_beta.teammentor
net\TM40\TM_4_0_GraphDB\.tmCache\Lib_UNO' to contain the string/array '.tmCache
_TM_3_5_Content'
   at String.assert_Contains (c:\TeamMentor\TMDEVRO-Site_beta.teammentor.net\TM
0\TM_4_0_GraphDB\node_modules\fluentnode\src\assert\assert_String.litcoffee:12:
)
   at c:\TeamMentor\TMDEVRO-Site_beta.teammentor.net\TM40\TM_4_0_GraphDB\test\s
rvices\Content-Service.test.coffee:26:16
   at c:\TeamMentor\TMDEVRO-Site_beta.teammentor.net\TM40\TM_4_0_GraphDB\src\se
vices\Content-Service.coffee:22:9
   at Config_Service.get_Config (c:\TeamMentor\TMDEVRO-Site_beta.teammentor.net
TM40\TM_4_0_GraphDB\src\services\Config-Service.coffee:14:7)
   at Config_Service.get_Config (c:\TeamMentor\TMDEVRO-Site_beta.teammentor.net
TM40\TM_4_0_GraphDB\src\services\Config-Service.coffee:2:1)
   at Content_Service.library_Folder (c:\TeamMentor\TMDEVRO-Site_beta.teammento
.net\TM40\TM_4_0_GraphDB\src\services\Content-Service.coffee:17:21)
   at Content_Service.library_Folder (c:\TeamMentor\TMDEVRO-Site_beta.teammento
.net\TM40\TM_4_0_GraphDB\src\services\Content-Service.coffee:1:1)
   at Content_Service.<anonymous> (c:\TeamMentor\TMDEVRO-Site_beta.teammentor.n
t\TM40\TM_4_0_GraphDB\test\services\Content-Service.test.coffee:24:9)
   at global.using (c:\TeamMentor\TMDEVRO-Site_beta.teammentor.net\TM40\TM_4_0_
raphDB\node_modules\fluentnode\src\globals.litcoffee:46:16)
   at Context.<anonymous> (c:\TeamMentor\TMDEVRO-Site_beta.teammentor.net\TM40\
M_4_0_GraphDB\test\services\Content-Service.test.coffee:23:5)
   at Test.Runnable.run (c:\TeamMentor\TMDEVRO-Site_beta.teammentor.net\TM40\TM
4_0_GraphDB\node_modules\mocha\lib\runnable.js:218:15)
   at Runner.runTest (c:\TeamMentor\TMDEVRO-Site_beta.teammentor.net\TM40\TM_4_
_GraphDB\node_modules\mocha\lib\runner.js:374:10)
   at c:\TeamMentor\TMDEVRO-Site_beta.teammentor.net\TM40\TM_4_0_GraphDB\node_m
dules\mocha\lib\runner.js:452:12
   at next (c:\TeamMentor\TMDEVRO-Site_beta.teammentor.net\TM40\TM_4_0_GraphDB\
ode_modules\mocha\lib\runner.js:299:14)
   at c:\TeamMentor\TMDEVRO-Site_beta.teammentor.net\TM40\TM_4_0_GraphDB\node_m
dules\mocha\lib\runner.js:309:7
   at next (c:\TeamMentor\TMDEVRO-Site_beta.teammentor.net\TM40\TM_4_0_GraphDB\
ode_modules\mocha\lib\runner.js:248:23)
   at Object._onImmediate (c:\TeamMentor\TMDEVRO-Site_beta.teammentor.net\TM40\
M_4_0_GraphDB\node_modules\mocha\lib\runner.js:276:5)
   at processImmediate [as _immediateCallback] (timers.js:354:15)




pm ERR! Test failed.  See above for more details.
pm ERR! not ok code 0

dministrator@WIN-2F62C9N5USL /c/TeamMentor/TMDEVRO-Site_beta.teammentor.net/TM4
/TM_4_0_GraphDB (master)
```

**Comment by roman87** [comment]
I know why the second one fails. Probably not the best test if we assume something to be in the config file. But the first one should not time out.

**Comment by DinisCruz** [comment]
I just fixed the 2nd one, it's the path differences between windows and osx

I think the first one could be caused by a permission issue in windows (that test starts the server, and in windows there are issues when opening ports from userland).

**Comment by romichg** [comment]
fixed
