### ISSUE TITLE
Specific search causes Express error

### ISSUE THREAD

**Issue by DinisCruz** [TeamMentor/TM_4_0_Design#421]
Searching for **sdfasdf%3Casdf98y345£$%@$£^£$%&** (as in **http://localhost:1337/search?text=sdfasdf%3Casdf98y345£$%@$£^£$%&**) will cause an  

Here is the error we get

```sh
TypeError: Failed to decode param 'sdfasdf%3Casdf98y345%C2%A3$%@$%C2%A3^%C2%A3$%'
  at decode_param (/Users/diniscruz/GitHub_REPOS/TM_4_0_QA/TM_4_0_GraphDB/node_modules/express/lib/router/layer.js:162:15)
  at Layer.match (/Users/diniscruz/GitHub_REPOS/TM_4_0_QA/TM_4_0_GraphDB/node_modules/express/lib/router/layer.js:136:11)
  at matchLayer (/Users/diniscruz/GitHub_REPOS/TM_4_0_QA/TM_4_0_GraphDB/node_modules/express/lib/router/index.js:545:18)
  at next (/Users/diniscruz/GitHub_REPOS/TM_4_0_QA/TM_4_0_GraphDB/node_modules/express/lib/router/index.js:206:15)
  at jsonParser (/Users/diniscruz/GitHub_REPOS/TM_4_0_QA/TM_4_0_GraphDB/node_modules/body-parser/lib/types/json.js:83:36)
  at Layer.handle [as handle_request] (/Users/diniscruz/GitHub_REPOS/TM_4_0_QA/TM_4_0_GraphDB/node_modules/express/lib/router/layer.js:82:5)
  at trim_prefix (/Users/diniscruz/GitHub_REPOS/TM_4_0_QA/TM_4_0_GraphDB/node_modules/express/lib/router/index.js:302:13)
  at /Users/diniscruz/GitHub_REPOS/TM_4_0_QA/TM_4_0_GraphDB/node_modules/express/lib/router/index.js:270:7
  at Function.proto.process_params (/Users/diniscruz/GitHub_REPOS/TM_4_0_QA/TM_4_0_GraphDB/node_modules/express/lib/router/index.js:321:12)
  at next (/Users/diniscruz/GitHub_REPOS/TM_4_0_QA/TM_4_0_GraphDB/node_modules/express/lib/router/index.js:261:10)
  at urlencodedParser (/Users/diniscruz/GitHub_REPOS/TM_4_0_QA/TM_4_0_GraphDB/node_modules/body-parser/lib/types/urlencoded.js:72:36)
  at Layer.handle [as handle_request] (/Users/diniscruz/GitHub_REPOS/TM_4_0_QA/TM_4_0_GraphDB/node_modules/express/lib/router/layer.js:82:5)
  at trim_prefix (/Users/diniscruz/GitHub_REPOS/TM_4_0_QA/TM_4_0_GraphDB/node_modules/express/lib/router/index.js:302:13)
  at /Users/diniscruz/GitHub_REPOS/TM_4_0_QA/TM_4_0_GraphDB/node_modules/express/lib/router/index.js:270:7
  at Function.proto.process_params (/Users/diniscruz/GitHub_REPOS/TM_4_0_QA/TM_4_0_GraphDB/node_modules/express/lib/router/index.js:321:12)
  at next (/Users/diniscruz/GitHub_REPOS/TM_4_0_QA/TM_4_0_GraphDB/node_modules/express/lib/router/index.js:261:10)
  at compression (/Users/diniscruz/GitHub_REPOS/TM_4_0_QA/TM_4_0_GraphDB/node_modules/compression/index.js:207:5)
  at Layer.handle [as handle_request] (/Users/diniscruz/GitHub_REPOS/TM_4_0_QA/TM_4_0_GraphDB/node_modules/express/lib/router/layer.js:82:5)
  at trim_prefix (/Users/diniscruz/GitHub_REPOS/TM_4_0_QA/TM_4_0_GraphDB/node_modules/express/lib/router/index.js:302:13)
  at /Users/diniscruz/GitHub_REPOS/TM_4_0_QA/TM_4_0_GraphDB/node_modules/express/lib/router/index.js:270:7
  at Function.proto.process_params (/Users/diniscruz/GitHub_REPOS/TM_4_0_QA/TM_4_0_GraphDB/node_modules/express/lib/router/index.js:321:12)
  at next (/Users/diniscruz/GitHub_REPOS/TM_4_0_QA/TM_4_0_GraphDB/node_modules/express/lib/router/index.js:261:10)
  at expressInit (/Users/diniscruz/GitHub_REPOS/TM_4_0_QA/TM_4_0_GraphDB/node_modules/express/lib/middleware/init.js:23:5)
  at Layer.handle [as handle_request] (/Users/diniscruz/GitHub_REPOS/TM_4_0_QA/TM_4_0_GraphDB/node_modules/express/lib/router/layer.js:82:5)
  at trim_prefix (/Users/diniscruz/GitHub_REPOS/TM_4_0_QA/TM_4_0_GraphDB/node_modules/express/lib/router/index.js:302:13)
  at /Users/diniscruz/GitHub_REPOS/TM_4_0_QA/TM_4_0_GraphDB/node_modules/express/lib/router/index.js:270:7
  at Function.proto.process_params (/Users/diniscruz/GitHub_REPOS/TM_4_0_QA/TM_4_0_GraphDB/node_modules/express/lib/router/index.js:321:12)
  at next (/Users/diniscruz/GitHub_REPOS/TM_4_0_QA/TM_4_0_GraphDB/node_modules/express/lib/router/index.js:261:10)
  at query (/Users/diniscruz/GitHub_REPOS/TM_4_0_QA/TM_4_0_GraphDB/node_modules/express/lib/middleware/query.js:28:5)
  at Layer.handle [as handle_request] (/Users/diniscruz/GitHub_REPOS/TM_4_0_QA/TM_4_0_GraphDB/node_modules/express/lib/router/layer.js:82:5)
  at trim_prefix (/Users/diniscruz/GitHub_REPOS/TM_4_0_QA/TM_4_0_GraphDB/node_modules/express/lib/router/index.js:302:13)
  at /Users/diniscruz/GitHub_REPOS/TM_4_0_QA/TM_4_0_GraphDB/node_modules/express/lib/router/index.js:270:7
  at Function.proto.process_params (/Users/diniscruz/GitHub_REPOS/TM_4_0_QA/TM_4_0_GraphDB/node_modules/express/lib/router/index.js:321:12)
  at next (/Users/diniscruz/GitHub_REPOS/TM_4_0_QA/TM_4_0_GraphDB/node_modules/express/lib/router/index.js:261:10)
  at Function.proto.handle (/Users/diniscruz/GitHub_REPOS/TM_4_0_QA/TM_4_0_GraphDB/node_modules/express/lib/router/index.js:166:3)
  at EventEmitter.app.handle (/Users/diniscruz/GitHub_REPOS/TM_4_0_QA/TM_4_0_GraphDB/node_modules/express/lib/application.js:141:10)
  at Server.app (/Users/diniscruz/GitHub_REPOS/TM_4_0_QA/TM_4_0_GraphDB/node_modules/express/lib/express.js:28:9)
  at Server.emit (events.js:98:17)
  at HTTPParser.parser.onIncoming (http.js:2112:12)
  at HTTPParser.parserOnHeadersComplete [as onHeadersComplete] (http.js:121:23)
  at Socket.socket.ondata (http.js:1970:22)
  at TCP.onread (net.js:527:27)
```

The search UI handles it ok, but we need to find the root cause of this

![image](https://cloud.githubusercontent.com/assets/656739/6164102/fcf9b37a-b292-11e4-803c-a82ac5ec9550.png)

**Comment by DinisCruz** [comment]
it looks like the prob is with **$%** 

For example **http://localhost:1332/search/query_from_text_search/$%** results in:

![image](https://cloud.githubusercontent.com/assets/656739/6164245/24293720-b295-11e4-9438-76c568171ba0.png)

Seems to happen everywhere:

**http://localhost:1332/data/id/%24%25** works ok (with those values encoded)

![image](https://cloud.githubusercontent.com/assets/656739/6164264/5acc17fc-b295-11e4-8206-7a4f363664f2.png)

**http://localhost:1332/data/id/$%** throws the same error

![image](https://cloud.githubusercontent.com/assets/656739/6164278/76ecf9e2-b295-11e4-82d0-d133db396906.png)

**Comment by DinisCruz** [comment]
Here is a simple test that replicates the issue 
```coffee
  describe 'Issue 421 - Specific search causes Express error', (done)->

    mock_app = null

    before ->
      app      = new express()
      app.get '/', (req,res)-> res.send '42 is the answer'
      app.get '/:id', (req,res)-> res.send 'throws with $%'
      app.use (err, req, res, next)->
          #console.error(err.stack)
          res.status(500)
             .send(err.message)

      mock_app = supertest(app)

    it '/', (done)->
      mock_app.get('/')
              .expect(200)
              .end (err,res)->
                res.text.assert_Is '42 is the answer'
                done()

    it '/$%', (done)->
      mock_app.get('/$%')
              .expect(500)
              .end (err,res)->
                res.text.assert_Is "Failed to decode param '$%'"
                done()
```

Uncommenting the ```#console.error(err.stack)``` line will show the detailed stack trace:

![image](https://cloud.githubusercontent.com/assets/656739/6164865/191f1984-b29b-11e4-9b5d-708a8a66462a.png)

Looks like the error is happening inside the **decodeURIComponent** native EcmaScript.js function:

![image](https://cloud.githubusercontent.com/assets/656739/6164882/312fc53c-b29b-11e4-9373-65f60c75c952.png)

**Comment by romichg** [comment]
@DinisCruz  this is fixed? Right?

**Comment by romichg** [comment]
This is fixed
