### ISSUE TITLE
Error running tests in the latest version of the GraphDatabase

### ISSUE THREAD

**Issue by michaelhidalgo** [TeamMentor/TM_4_0_Design#516]
I get the latest version of the GraphDatabase, I deleted the cache did a clean install and ran npm test and 7 test are failing. @DinisCruz, could it be that something is pending to push?

Those test are related to the Search-API

```javascript
 7 failing

  1) | api | Search-API.test query_from_text_search:
     Uncaught TypeError: Cannot call method 'assert_Is' of undefined
    at [object Object].successCallback (/Users/michaelhidalgo/TM4.0/TM_4_0_GraphDB/test/api/Search-API.test.coffee:71:16)
    at Object.obj.on.response (/Users/michaelhidalgo/TM4.0/TM_4_0_GraphDB/node_modules/swagger-client/lib/swagger-client.js:2623:24)
    at EventEmitter.res.response (/Users/michaelhidalgo/TM4.0/TM_4_0_GraphDB/node_modules/swagger-client/lib/swagger-client.js:2956:19)
    at EventEmitter.emit (events.js:95:17)
    at emit (/Users/michaelhidalgo/TM4.0/TM_4_0_GraphDB/node_modules/swagger-client/node_modules/shred/lib/shred/request.js:456:21)
    at /Users/michaelhidalgo/TM4.0/TM_4_0_GraphDB/node_modules/swagger-client/node_modules/shred/lib/shred/request.js:476:9
    at setBodyAndFinish (/Users/michaelhidalgo/TM4.0/TM_4_0_GraphDB/node_modules/swagger-client/node_modules/shred/lib/shred/response.js:103:7)
    at IncomingMessage.<anonymous> (/Users/michaelhidalgo/TM4.0/TM_4_0_GraphDB/node_modules/swagger-client/node_modules/shred/lib/shred/response.js:120:7)
    at IncomingMessage.EventEmitter.emit (events.js:117:20)
    at _stream_readable.js:919:16
    at process._tickCallback (node.js:419:13)
  

  2) | services | data | Search-Service.test | search_Using_Text:
     AssertionError: [assert_Not_Empty]
    at Array.assert_Size_Is_Not (/Users/michaelhidalgo/TM4.0/TM_4_0_GraphDB/node_modules/fluentnode/src/assert/assert_Array.litcoffee:81:14)
    at Array.assert_Not_Empty (/Users/michaelhidalgo/TM4.0/TM_4_0_GraphDB/node_modules/fluentnode/src/assert/assert_Array.litcoffee:47:8)
    at /Users/michaelhidalgo/TM4.0/TM_4_0_GraphDB/test/services/data/Search-Service.test.coffee:73:15
    at /Users/michaelhidalgo/TM4.0/TM_4_0_GraphDB/src/services/data/Search-Service.coffee:31:7
    at Search_Text_Service.consolidate_Scores (/Users/michaelhidalgo/TM4.0/TM_4_0_GraphDB/src/services/text-search/Search-Text-Service.coffee:100:5)
    at Search_Text_Service.consolidate_Scores (/Users/michaelhidalgo/TM4.0/TM_4_0_GraphDB/src/services/text-search/Search-Text-Service.coffee:1:1)
    at /Users/michaelhidalgo/TM4.0/TM_4_0_GraphDB/src/services/text-search/Search-Text-Service.coffee:75:9
    at /Users/michaelhidalgo/TM4.0/TM_4_0_GraphDB/node_modules/async/lib/async.js:157:25
    at /Users/michaelhidalgo/TM4.0/TM_4_0_GraphDB/src/services/text-search/Search-Text-Service.coffee:72:9
    at /Users/michaelhidalgo/TM4.0/TM_4_0_GraphDB/src/services/text-search/Search-Text-Service.coffee:61:7
    at Search_Text_Service.search_Mappings (/Users/michaelhidalgo/TM4.0/TM_4_0_GraphDB/src/services/text-search/Search-Text-Service.coffee:26:5)
    at Search_Text_Service.search_Mappings (/Users/michaelhidalgo/TM4.0/TM_4_0_GraphDB/src/services/text-search/Search-Text-Service.coffee:1:1)
    at Search_Text_Service.word_Score (/Users/michaelhidalgo/TM4.0/TM_4_0_GraphDB/src/services/text-search/Search-Text-Service.coffee:35:7)
    at Search_Text_Service.word_Score (/Users/michaelhidalgo/TM4.0/TM_4_0_GraphDB/src/services/text-search/Search-Text-Service.coffee:1:1)
    at /Users/michaelhidalgo/TM4.0/TM_4_0_GraphDB/src/services/text-search/Search-Text-Service.coffee:70:8
    at iterate (/Users/michaelhidalgo/TM4.0/TM_4_0_GraphDB/node_modules/async/lib/async.js:149:13)
    at Object.async.eachSeries (/Users/michaelhidalgo/TM4.0/TM_4_0_GraphDB/node_modules/async/lib/async.js:165:9)
    at Search_Text_Service.words_Score (/Users/michaelhidalgo/TM4.0/TM_4_0_GraphDB/src/services/text-search/Search-Text-Service.coffee:74:11)
    at Search_Text_Service.words_Score (/Users/michaelhidalgo/TM4.0/TM_4_0_GraphDB/src/services/text-search/Search-Text-Service.coffee:1:1)
    at Search_Service.search_Using_Text (/Users/michaelhidalgo/TM4.0/TM_4_0_GraphDB/src/services/data/Search-Service.coffee:30:31)
    at Search_Service.search_Using_Text (/Users/michaelhidalgo/TM4.0/TM_4_0_GraphDB/src/services/data/Search-Service.coffee:1:1)
    at Context.<anonymous> (/Users/michaelhidalgo/TM4.0/TM_4_0_GraphDB/test/services/data/Search-Service.test.coffee:72:19)
    at Test.Runnable.run (/Users/michaelhidalgo/TM4.0/TM_4_0_GraphDB/node_modules/mocha/lib/runnable.js:233:15)
    at Runner.runTest (/Users/michaelhidalgo/TM4.0/TM_4_0_GraphDB/node_modules/mocha/lib/runner.js:387:10)
    at /Users/michaelhidalgo/TM4.0/TM_4_0_GraphDB/node_modules/mocha/lib/runner.js:470:12
    at next (/Users/michaelhidalgo/TM4.0/TM_4_0_GraphDB/node_modules/mocha/lib/runner.js:312:14)
    at /Users/michaelhidalgo/TM4.0/TM_4_0_GraphDB/node_modules/mocha/lib/runner.js:322:7
    at next (/Users/michaelhidalgo/TM4.0/TM_4_0_GraphDB/node_modules/mocha/lib/runner.js:257:23)
    at Object._onImmediate (/Users/michaelhidalgo/TM4.0/TM_4_0_GraphDB/node_modules/mocha/lib/runner.js:289:5)
    at processImmediate [as _immediateCallback] (timers.js:336:15)
  

  3) | services | data | Search-Service.test | query_From_Text_Search:
     Uncaught TypeError: Cannot call method 'assert_Is' of null
    at /Users/michaelhidalgo/TM4.0/TM_4_0_GraphDB/test/services/data/Search-Service.test.coffee:94:16
    at /Users/michaelhidalgo/TM4.0/TM_4_0_GraphDB/src/services/data/Search-Service.coffee:59:11
    at /Users/michaelhidalgo/TM4.0/TM_4_0_GraphDB/src/services/data/Search-Service.coffee:31:7
    at Search_Text_Service.consolidate_Scores (/Users/michaelhidalgo/TM4.0/TM_4_0_GraphDB/src/services/text-search/Search-Text-Service.coffee:100:5)
    at Search_Text_Service.consolidate_Scores (/Users/michaelhidalgo/TM4.0/TM_4_0_GraphDB/src/services/text-search/Search-Text-Service.coffee:1:1)
    at /Users/michaelhidalgo/TM4.0/TM_4_0_GraphDB/src/services/text-search/Search-Text-Service.coffee:75:9
    at /Users/michaelhidalgo/TM4.0/TM_4_0_GraphDB/node_modules/async/lib/async.js:157:25
    at /Users/michaelhidalgo/TM4.0/TM_4_0_GraphDB/src/services/text-search/Search-Text-Service.coffee:72:9
    at /Users/michaelhidalgo/TM4.0/TM_4_0_GraphDB/src/services/text-search/Search-Text-Service.coffee:61:7
    at Search_Text_Service.search_Mappings (/Users/michaelhidalgo/TM4.0/TM_4_0_GraphDB/src/services/text-search/Search-Text-Service.coffee:26:5)
    at Search_Text_Service.search_Mappings (/Users/michaelhidalgo/TM4.0/TM_4_0_GraphDB/src/services/text-search/Search-Text-Service.coffee:1:1)
    at Search_Text_Service.word_Score (/Users/michaelhidalgo/TM4.0/TM_4_0_GraphDB/src/services/text-search/Search-Text-Service.coffee:35:7)
    at Search_Text_Service.word_Score (/Users/michaelhidalgo/TM4.0/TM_4_0_GraphDB/src/services/text-search/Search-Text-Service.coffee:1:1)
    at /Users/michaelhidalgo/TM4.0/TM_4_0_GraphDB/src/services/text-search/Search-Text-Service.coffee:70:8
    at iterate (/Users/michaelhidalgo/TM4.0/TM_4_0_GraphDB/node_modules/async/lib/async.js:149:13)
    at Object.async.eachSeries (/Users/michaelhidalgo/TM4.0/TM_4_0_GraphDB/node_modules/async/lib/async.js:165:9)
    at Search_Text_Service.words_Score (/Users/michaelhidalgo/TM4.0/TM_4_0_GraphDB/src/services/text-search/Search-Text-Service.coffee:74:11)
    at Search_Text_Service.words_Score (/Users/michaelhidalgo/TM4.0/TM_4_0_GraphDB/src/services/text-search/Search-Text-Service.coffee:1:1)
    at Search_Service.search_Using_Text (/Users/michaelhidalgo/TM4.0/TM_4_0_GraphDB/src/services/data/Search-Service.coffee:30:31)
    at Search_Service.search_Using_Text (/Users/michaelhidalgo/TM4.0/TM_4_0_GraphDB/src/services/data/Search-Service.coffee:1:1)
    at /Users/michaelhidalgo/TM4.0/TM_4_0_GraphDB/src/services/data/Search-Service.coffee:57:8
    at /Users/michaelhidalgo/TM4.0/TM_4_0_GraphDB/src/services/graph/Graph-Find.coffee:207:9
    at CallbackStream.<anonymous> (/Users/michaelhidalgo/TM4.0/TM_4_0_GraphDB/node_modules/levelgraph/node_modules/callback-stream/index.js:23:5)
    at CallbackStream.EventEmitter.emit (events.js:117:20)
    at finishMaybe (_stream_writable.js:360:12)
    at endWritable (_stream_writable.js:367:3)
    at CallbackStream.Writable.end (_stream_writable.js:345:5)
    at ReadStream.onend (/Users/michaelhidalgo/TM4.0/TM_4_0_GraphDB/node_modules/levelgraph/node_modules/readable-stream/lib/_stream_readable.js:523:10)
    at ReadStream.g (events.js:180:16)
    at ReadStream.EventEmitter.emit (events.js:92:17)
    at /Users/michaelhidalgo/TM4.0/TM_4_0_GraphDB/node_modules/levelgraph/node_modules/readable-stream/lib/_stream_readable.js:965:16
    at process._tickCallback (node.js:419:13)
  

  4) | services | text-search | Search-Text-Service.test word_Data:
     TypeError: Cannot call method 'keys' of undefined
    at /Users/michaelhidalgo/TM4.0/TM_4_0_GraphDB/test/services/text-search/Search-Text-Service.test.coffee:18:15
    at /Users/michaelhidalgo/TM4.0/TM_4_0_GraphDB/src/services/text-search/Search-Text-Service.coffee:30:7
    at Search_Text_Service.search_Mappings (/Users/michaelhidalgo/TM4.0/TM_4_0_GraphDB/src/services/text-search/Search-Text-Service.coffee:18:14)
    at Search_Text_Service.search_Mappings (/Users/michaelhidalgo/TM4.0/TM_4_0_GraphDB/src/services/text-search/Search-Text-Service.coffee:1:1)
    at Search_Text_Service.word_Data (/Users/michaelhidalgo/TM4.0/TM_4_0_GraphDB/src/services/text-search/Search-Text-Service.coffee:29:7)
    at Search_Text_Service.word_Data (/Users/michaelhidalgo/TM4.0/TM_4_0_GraphDB/src/services/text-search/Search-Text-Service.coffee:1:1)
    at Context.<anonymous> (/Users/michaelhidalgo/TM4.0/TM_4_0_GraphDB/test/services/text-search/Search-Text-Service.test.coffee:17:17)
    at Test.Runnable.run (/Users/michaelhidalgo/TM4.0/TM_4_0_GraphDB/node_modules/mocha/lib/runnable.js:233:15)
    at Runner.runTest (/Users/michaelhidalgo/TM4.0/TM_4_0_GraphDB/node_modules/mocha/lib/runner.js:387:10)
    at /Users/michaelhidalgo/TM4.0/TM_4_0_GraphDB/node_modules/mocha/lib/runner.js:470:12
    at next (/Users/michaelhidalgo/TM4.0/TM_4_0_GraphDB/node_modules/mocha/lib/runner.js:312:14)
    at /Users/michaelhidalgo/TM4.0/TM_4_0_GraphDB/node_modules/mocha/lib/runner.js:322:7
    at next (/Users/michaelhidalgo/TM4.0/TM_4_0_GraphDB/node_modules/mocha/lib/runner.js:257:23)
    at Object._onImmediate (/Users/michaelhidalgo/TM4.0/TM_4_0_GraphDB/node_modules/mocha/lib/runner.js:289:5)
    at processImmediate [as _immediateCallback] (timers.js:336:15)
  

  5) | services | text-search | Search-Text-Service.test word_Score:
     AssertionError: [assert_Not_Empty]
    at Array.assert_Size_Is_Not (/Users/michaelhidalgo/TM4.0/TM_4_0_GraphDB/node_modules/fluentnode/src/assert/assert_Array.litcoffee:81:14)
    at Array.assert_Not_Empty (/Users/michaelhidalgo/TM4.0/TM_4_0_GraphDB/node_modules/fluentnode/src/assert/assert_Array.litcoffee:47:8)
    at /Users/michaelhidalgo/TM4.0/TM_4_0_GraphDB/test/services/text-search/Search-Text-Service.test.coffee:23:15
    at /Users/michaelhidalgo/TM4.0/TM_4_0_GraphDB/src/services/text-search/Search-Text-Service.coffee:61:7
    at Search_Text_Service.search_Mappings (/Users/michaelhidalgo/TM4.0/TM_4_0_GraphDB/src/services/text-search/Search-Text-Service.coffee:18:14)
    at Search_Text_Service.search_Mappings (/Users/michaelhidalgo/TM4.0/TM_4_0_GraphDB/src/services/text-search/Search-Text-Service.coffee:1:1)
    at Search_Text_Service.word_Score (/Users/michaelhidalgo/TM4.0/TM_4_0_GraphDB/src/services/text-search/Search-Text-Service.coffee:35:7)
    at Search_Text_Service.word_Score (/Users/michaelhidalgo/TM4.0/TM_4_0_GraphDB/src/services/text-search/Search-Text-Service.coffee:1:1)
    at Context.<anonymous> (/Users/michaelhidalgo/TM4.0/TM_4_0_GraphDB/test/services/text-search/Search-Text-Service.test.coffee:22:17)
    at Test.Runnable.run (/Users/michaelhidalgo/TM4.0/TM_4_0_GraphDB/node_modules/mocha/lib/runnable.js:233:15)
    at Runner.runTest (/Users/michaelhidalgo/TM4.0/TM_4_0_GraphDB/node_modules/mocha/lib/runner.js:387:10)
    at /Users/michaelhidalgo/TM4.0/TM_4_0_GraphDB/node_modules/mocha/lib/runner.js:470:12
    at next (/Users/michaelhidalgo/TM4.0/TM_4_0_GraphDB/node_modules/mocha/lib/runner.js:312:14)
    at /Users/michaelhidalgo/TM4.0/TM_4_0_GraphDB/node_modules/mocha/lib/runner.js:322:7
    at next (/Users/michaelhidalgo/TM4.0/TM_4_0_GraphDB/node_modules/mocha/lib/runner.js:257:23)
    at Object._onImmediate (/Users/michaelhidalgo/TM4.0/TM_4_0_GraphDB/node_modules/mocha/lib/runner.js:289:5)
    at processImmediate [as _immediateCallback] (timers.js:336:15)
  

  6) | services | text-search | Search-Text-Service.test words_Score:
     AssertionError: [assert_Not_Empty]
    at Array.assert_Size_Is_Not (/Users/michaelhidalgo/TM4.0/TM_4_0_GraphDB/node_modules/fluentnode/src/assert/assert_Array.litcoffee:81:14)
    at Array.assert_Not_Empty (/Users/michaelhidalgo/TM4.0/TM_4_0_GraphDB/node_modules/fluentnode/src/assert/assert_Array.litcoffee:47:8)
    at /Users/michaelhidalgo/TM4.0/TM_4_0_GraphDB/test/services/text-search/Search-Text-Service.test.coffee:28:15
    at Search_Text_Service.consolidate_Scores (/Users/michaelhidalgo/TM4.0/TM_4_0_GraphDB/src/services/text-search/Search-Text-Service.coffee:100:5)
    at Search_Text_Service.consolidate_Scores (/Users/michaelhidalgo/TM4.0/TM_4_0_GraphDB/src/services/text-search/Search-Text-Service.coffee:1:1)
    at /Users/michaelhidalgo/TM4.0/TM_4_0_GraphDB/src/services/text-search/Search-Text-Service.coffee:75:9
    at /Users/michaelhidalgo/TM4.0/TM_4_0_GraphDB/node_modules/async/lib/async.js:157:25
    at /Users/michaelhidalgo/TM4.0/TM_4_0_GraphDB/src/services/text-search/Search-Text-Service.coffee:72:9
    at /Users/michaelhidalgo/TM4.0/TM_4_0_GraphDB/src/services/text-search/Search-Text-Service.coffee:61:7
    at Search_Text_Service.search_Mappings (/Users/michaelhidalgo/TM4.0/TM_4_0_GraphDB/src/services/text-search/Search-Text-Service.coffee:18:14)
    at Search_Text_Service.search_Mappings (/Users/michaelhidalgo/TM4.0/TM_4_0_GraphDB/src/services/text-search/Search-Text-Service.coffee:1:1)
    at Search_Text_Service.word_Score (/Users/michaelhidalgo/TM4.0/TM_4_0_GraphDB/src/services/text-search/Search-Text-Service.coffee:35:7)
    at Search_Text_Service.word_Score (/Users/michaelhidalgo/TM4.0/TM_4_0_GraphDB/src/services/text-search/Search-Text-Service.coffee:1:1)
    at /Users/michaelhidalgo/TM4.0/TM_4_0_GraphDB/src/services/text-search/Search-Text-Service.coffee:70:8
    at iterate (/Users/michaelhidalgo/TM4.0/TM_4_0_GraphDB/node_modules/async/lib/async.js:149:13)
    at /Users/michaelhidalgo/TM4.0/TM_4_0_GraphDB/node_modules/async/lib/async.js:160:25
    at /Users/michaelhidalgo/TM4.0/TM_4_0_GraphDB/src/services/text-search/Search-Text-Service.coffee:69:16
    at iterate (/Users/michaelhidalgo/TM4.0/TM_4_0_GraphDB/node_modules/async/lib/async.js:149:13)
    at /Users/michaelhidalgo/TM4.0/TM_4_0_GraphDB/node_modules/async/lib/async.js:160:25
    at /Users/michaelhidalgo/TM4.0/TM_4_0_GraphDB/src/services/text-search/Search-Text-Service.coffee:69:16
    at iterate (/Users/michaelhidalgo/TM4.0/TM_4_0_GraphDB/node_modules/async/lib/async.js:149:13)
    at /Users/michaelhidalgo/TM4.0/TM_4_0_GraphDB/node_modules/async/lib/async.js:160:25
    at /Users/michaelhidalgo/TM4.0/TM_4_0_GraphDB/src/services/text-search/Search-Text-Service.coffee:72:9
    at /Users/michaelhidalgo/TM4.0/TM_4_0_GraphDB/src/services/text-search/Search-Text-Service.coffee:61:7
    at Search_Text_Service.search_Mappings (/Users/michaelhidalgo/TM4.0/TM_4_0_GraphDB/src/services/text-search/Search-Text-Service.coffee:18:14)
    at Search_Text_Service.search_Mappings (/Users/michaelhidalgo/TM4.0/TM_4_0_GraphDB/src/services/text-search/Search-Text-Service.coffee:1:1)
    at Search_Text_Service.word_Score (/Users/michaelhidalgo/TM4.0/TM_4_0_GraphDB/src/services/text-search/Search-Text-Service.coffee:35:7)
    at Search_Text_Service.word_Score (/Users/michaelhidalgo/TM4.0/TM_4_0_GraphDB/src/services/text-search/Search-Text-Service.coffee:1:1)
    at /Users/michaelhidalgo/TM4.0/TM_4_0_GraphDB/src/services/text-search/Search-Text-Service.coffee:70:8
    at iterate (/Users/michaelhidalgo/TM4.0/TM_4_0_GraphDB/node_modules/async/lib/async.js:149:13)
    at Object.async.eachSeries (/Users/michaelhidalgo/TM4.0/TM_4_0_GraphDB/node_modules/async/lib/async.js:165:9)
    at Search_Text_Service.words_Score (/Users/michaelhidalgo/TM4.0/TM_4_0_GraphDB/src/services/text-search/Search-Text-Service.coffee:74:11)
    at Search_Text_Service.words_Score (/Users/michaelhidalgo/TM4.0/TM_4_0_GraphDB/src/services/text-search/Search-Text-Service.coffee:1:1)
    at Context.<anonymous> (/Users/michaelhidalgo/TM4.0/TM_4_0_GraphDB/test/services/text-search/Search-Text-Service.test.coffee:27:17)
    at Test.Runnable.run (/Users/michaelhidalgo/TM4.0/TM_4_0_GraphDB/node_modules/mocha/lib/runnable.js:233:15)
    at Runner.runTest (/Users/michaelhidalgo/TM4.0/TM_4_0_GraphDB/node_modules/mocha/lib/runner.js:387:10)
    at /Users/michaelhidalgo/TM4.0/TM_4_0_GraphDB/node_modules/mocha/lib/runner.js:470:12
    at next (/Users/michaelhidalgo/TM4.0/TM_4_0_GraphDB/node_modules/mocha/lib/runner.js:312:14)
    at /Users/michaelhidalgo/TM4.0/TM_4_0_GraphDB/node_modules/mocha/lib/runner.js:322:7
    at next (/Users/michaelhidalgo/TM4.0/TM_4_0_GraphDB/node_modules/mocha/lib/runner.js:257:23)
    at Object._onImmediate (/Users/michaelhidalgo/TM4.0/TM_4_0_GraphDB/node_modules/mocha/lib/runner.js:289:5)
    at processImmediate [as _immediateCallback] (timers.js:336:15)
  

  7) | services | text-search | Search-Text-Service.test words_List :
     AssertionError: [assert_Size_Is_Bigger_Than] expected bigger than 100, but it was 0 
    at Boolean.assert_Is_True (/Users/michaelhidalgo/TM4.0/TM_4_0_GraphDB/node_modules/fluentnode/src/assert/assert_Boolean.litcoffee:22:14)
    at Array.assert_Size_Is_Bigger_Than (/Users/michaelhidalgo/TM4.0/TM_4_0_GraphDB/node_modules/fluentnode/src/assert/assert_Array.litcoffee:66:25)
    at /Users/michaelhidalgo/TM4.0/TM_4_0_GraphDB/test/services/text-search/Search-Text-Service.test.coffee:33:13
    at /Users/michaelhidalgo/TM4.0/TM_4_0_GraphDB/src/services/text-search/Search-Text-Service.coffee:105:7
    at Search_Text_Service.search_Mappings (/Users/michaelhidalgo/TM4.0/TM_4_0_GraphDB/src/services/text-search/Search-Text-Service.coffee:18:14)
    at Search_Text_Service.search_Mappings (/Users/michaelhidalgo/TM4.0/TM_4_0_GraphDB/src/services/text-search/Search-Text-Service.coffee:1:1)
    at Search_Text_Service.words_List (/Users/michaelhidalgo/TM4.0/TM_4_0_GraphDB/src/services/text-search/Search-Text-Service.coffee:103:7)
    at Search_Text_Service.words_List (/Users/michaelhidalgo/TM4.0/TM_4_0_GraphDB/src/services/text-search/Search-Text-Service.coffee:1:1)
    at Context.<anonymous> (/Users/michaelhidalgo/TM4.0/TM_4_0_GraphDB/test/services/text-search/Search-Text-Service.test.coffee:32:17)
    at Test.Runnable.run (/Users/michaelhidalgo/TM4.0/TM_4_0_GraphDB/node_modules/mocha/lib/runnable.js:233:15)
    at Runner.runTest (/Users/michaelhidalgo/TM4.0/TM_4_0_GraphDB/node_modules/mocha/lib/runner.js:387:10)
    at /Users/michaelhidalgo/TM4.0/TM_4_0_GraphDB/node_modules/mocha/lib/runner.js:470:12
    at next (/Users/michaelhidalgo/TM4.0/TM_4_0_GraphDB/node_modules/mocha/lib/runner.js:312:14)
    at /Users/michaelhidalgo/TM4.0/TM_4_0_GraphDB/node_modules/mocha/lib/runner.js:322:7
    at next (/Users/michaelhidalgo/TM4.0/TM_4_0_GraphDB/node_modules/mocha/lib/runner.js:257:23)
    at Object._onImmediate (/Users/michaelhidalgo/TM4.0/TM_4_0_GraphDB/node_modules/mocha/lib/runner.js:289:5)
    at processImmediate [as _immediateCallback] (timers.js:336:15)
  



npm ERR! Test failed.  See above for more details.
npm ERR! not ok code 0
na:TM_4_0_GraphDB michaelhidalgo$ npm test

```

**Comment by roman87** [comment]
Did you run npm install?

**Comment by michaelhidalgo** [comment]
Yeah, I ran the npm update and I deleted the cache, I also ensured that I was running the latest version from master.

**Comment by roman87** [comment]
Can you try a fresh, brand new clone? i.e. git clone, npm install, npm test...

**Comment by michaelhidalgo** [comment]
I think it is a general issue. It also failed on Travis https://travis-ci.org/TeamMentor/TM_4_0_GraphDB

**Comment by DinisCruz** [comment]
yes @michaelhidalgo is correct, it is actually to do with the order of the tests (since one of the cache needed for the failed tests is created by an later test)

I'm fixing this now

this kind of issues will be addressed for good once I add an installer to download all library files and create all artifacts

**Comment by roman87** [comment]
Can't wait :) do we have an issue on that?

**Comment by DinisCruz** [comment]
yes (https://github.com/TeamMentor/TM_4_0_Design/issues/520)

**Comment by DinisCruz** [comment]
[latest push](https://travis-ci.org/TeamMentor/TM_4_0_GraphDB/builds/53841545) address this (with the build now passing on Travis)

![image](https://cloud.githubusercontent.com/assets/656739/6582318/80aa6c02-c754-11e4-9a15-3394f6a499a2.png)

**Comment by DinisCruz** [comment]
So I just run this commands and it worked:

```bash
mkdir 10-mar-2015
cd 10-mar-2015
git clone git@github.com:TeamMentor/TM_4_0_GraphDB.git
cd TM_4_0_GraphDB
npm install
npm test
```

here are the last lines of the **npm test** command

```
  ․ | services | text-search | Search-Artifacts-Service.test batch_Parse_All_Articles: 8035ms
    | services | text-search | Search-Artifacts-Service.test create_Search_Mappings: no key for raw_Articles_Html, so calculating them all
  ․ | services | text-search | Search-Artifacts-Service.test create_Search_Mappings: 826ms
  ․ | services | text-search | Search-Artifacts-Service.test parse_Article: 2ms
  ․ | services | text-search | Search-Artifacts-Service.test parse_Article_Html: 52ms
    | services | text-search | Search-Artifacts-Service.test parse_Articles: parse_Articles: 397ms
  ․ | services | text-search | Search-Artifacts-Service.test parse_Articles: 398ms
  ․ | services | text-search | Search-Artifacts-Service.test raw_Articles_Html: 283ms
  ․ | services | text-search | Search-Text-Service.test search_Mappings: 157ms
  ․ | services | text-search | Search-Text-Service.test word_Data: 2ms
  ․ | services | text-search | Search-Text-Service.test word_Score: 1ms
  ․ | services | text-search | Search-Text-Service.test words_Score: 2ms
    | services | text-search | Search-Text-Service.test words_List : there are 1692 unique words
  ․ | services | text-search | Search-Text-Service.test words_List : 7ms
  ․ | services | utils | Config-Service.test construtor: 0ms
  ․ | services | utils | Config-Service.test construtor (with params): 0ms
  ․ | services | utils | Config-Service.test config_File_Path: 0ms
  ․ | services | utils | Config-Service.test get_Config: 1ms
  ․ | services | utils | Config-Service.test get_Defaults: 0ms
  ․ | services | utils | Config-Service.test save_Config: 0ms

  173 passing (25s)
  1 pending
```

**Comment by michaelhidalgo** [comment]
Yeah, this issue is fixed.
