### ISSUE TITLE
GraphDB Crashes on Windows when going through the UI

### ISSUE THREAD

**Issue by roman87** [TeamMentor/TM_4_0_Design#740]
On a brand new box, using the ZIP file compiled on tm-dev-01. 
Installed node
![selection_185](https://cloud.githubusercontent.com/assets/1326120/7436710/2589d626-f01e-11e4-8326-7bf08770e639.png)

Starting both graphDb and TMDesign work fine.
![selection_186](https://cloud.githubusercontent.com/assets/1326120/7436712/31230c78-f01e-11e4-9813-402f86ceaf27.png)

However as soon as I login and hit index, or search for XSS I get the following error

Hitting "Index"
```
2015-05-01T20:19:52.203Z - info: Adding swagger support
2015-05-01T20:19:53.372Z - info: Server started at: http://localhost:1332
2015-05-01T20:19:58.175Z - info:  method=GET, url=/data/library_Query
2015-05-01T20:19:58.192Z - info:  method=GET, url=/convert/to_ids/query-6234f2d4
7eb7
c:\TEAM Mentor\TMSTG02_Site_beta.teammentor.net\TM40\TM_4_0_GraphDB\node_modules
\levelgraph\node_modules\leveldown\node_modules\bindings\bindings.js:83
        throw e
              ^
Error: %1 is not a valid Win32 application.
c:\TEAM Mentor\TMSTG02_Site_beta.teammentor.net\TM40\TM_4_0_GraphDB\node_modules
\levelgraph\node_modules\leveldown\build\Release\leveldown.node
  at Error (native)
  at Module.load (c:\TEAM Mentor\TMSTG02_Site_beta.teammentor.net\TM40\TM_4_0_Gr
aphDB\node_modules\coffee-script\lib\coffee-script\register.js:45:36)
  at Function.Module._load (module.js:310:12)
  at Module.require (module.js:365:17)
  at require (module.js:384:17)
  at bindings (c:\TEAM Mentor\TMSTG02_Site_beta.teammentor.net\TM40\TM_4_0_Graph
DB\node_modules\levelgraph\node_modules\leveldown\node_modules\bindings\bindings
.js:76:44)
  at Object.<anonymous> (c:\TEAM Mentor\TMSTG02_Site_beta.teammentor.net\TM40\TM
_4_0_GraphDB\node_modules\levelgraph\node_modules\leveldown\index.js:1:99)
  at Module._compile (module.js:460:26)
  at Object.Module._extensions..js (module.js:478:10)
  at Module.load (c:\TEAM Mentor\TMSTG02_Site_beta.teammentor.net\TM40\TM_4_0_Gr
aphDB\node_modules\coffee-script\lib\coffee-script\register.js:45:36)
  at Function.Module._load (module.js:310:12)
  at Module.require (module.js:365:17)
  at require (module.js:384:17)
  at Object.<anonymous> (c:\TEAM Mentor\TMSTG02_Site_beta.teammentor.net\TM40\TM
_4_0_GraphDB\node_modules\levelgraph\lib\getdb.js:27:18)
  at Module._compile (module.js:460:26)
  at Object.Module._extensions..js (module.js:478:10)
  at Module.load (c:\TEAM Mentor\TMSTG02_Site_beta.teammentor.net\TM40\TM_4_0_Gr
aphDB\node_modules\coffee-script\lib\coffee-script\register.js:45:36)
  at Function.Module._load (module.js:310:12)
  at Module.require (module.js:365:17)
  at require (module.js:384:17)
  at levelgraph (c:\TEAM Mentor\TMSTG02_Site_beta.teammentor.net\TM40\TM_4_0_Gra
phDB\node_modules\levelgraph\lib\levelgraph.js:70:20)
  at c:\TEAM Mentor\TMSTG02_Site_beta.teammentor.net\TM40\TM_4_0_GraphDB\src\ser
vices\graph\Graph-Service.coffee:29:15
  at process._tickCallback (node.js:355:11)


npm ERR! Windows_NT 6.3.9600
npm ERR! argv "c:\\Program Files\\nodejs\\node.exe" "c:\\Program Files\\nodejs\\
node_modules\\npm\\bin\\npm-cli.js" "start"
npm ERR! node v0.12.2
npm ERR! npm  v2.7.4
npm ERR! code ELIFECYCLE
npm ERR! TM_4_0_GraphDB@0.0.1 start: `node index.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the TM_4_0_GraphDB@0.0.1 start script 'node index.js'.
npm ERR! This is most likely a problem with the TM_4_0_GraphDB package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node index.js
npm ERR! You can get their info via:
npm ERR!     npm owner ls TM_4_0_GraphDB
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     c:\TEAM Mentor\TMSTG02_Site_beta.teammentor.net\TM40\TM_4_0_GraphDB
\npm-debug.log

Administrator@WIN-P3L0145SVLV /c/TEAM Mentor/TMSTG02_Site_beta.teammentor.net/TM
40/TM_4_0_GraphDB (master)
$
```

Searching for "XSS"

```
Hooking Console to Winston logger
[Logging-Service] console hooked
2015-05-01T20:23:15.065Z - info: Adding swagger support
2015-05-01T20:23:16.208Z - info: Server started at: http://localhost:1332
2015-05-01T20:23:21.674Z - info:  method=GET, url=/convert/to_ids/XSS
c:\TEAM Mentor\TMSTG02_Site_beta.teammentor.net\TM40\TM_4_0_GraphDB\node_modules
\levelgraph\node_modules\leveldown\node_modules\bindings\bindings.js:83
        throw e
              ^
Error: %1 is not a valid Win32 application.
c:\TEAM Mentor\TMSTG02_Site_beta.teammentor.net\TM40\TM_4_0_GraphDB\node_modules
\levelgraph\node_modules\leveldown\build\Release\leveldown.node
  at Error (native)
  at Module.load (c:\TEAM Mentor\TMSTG02_Site_beta.teammentor.net\TM40\TM_4_0_Gr
aphDB\node_modules\coffee-script\lib\coffee-script\register.js:45:36)
  at Function.Module._load (module.js:310:12)
  at Module.require (module.js:365:17)
  at require (module.js:384:17)
  at bindings (c:\TEAM Mentor\TMSTG02_Site_beta.teammentor.net\TM40\TM_4_0_Graph
DB\node_modules\levelgraph\node_modules\leveldown\node_modules\bindings\bindings
.js:76:44)
  at Object.<anonymous> (c:\TEAM Mentor\TMSTG02_Site_beta.teammentor.net\TM40\TM
_4_0_GraphDB\node_modules\levelgraph\node_modules\leveldown\index.js:1:99)
  at Module._compile (module.js:460:26)
  at Object.Module._extensions..js (module.js:478:10)
  at Module.load (c:\TEAM Mentor\TMSTG02_Site_beta.teammentor.net\TM40\TM_4_0_Gr
aphDB\node_modules\coffee-script\lib\coffee-script\register.js:45:36)
  at Function.Module._load (module.js:310:12)
  at Module.require (module.js:365:17)
  at require (module.js:384:17)
  at Object.<anonymous> (c:\TEAM Mentor\TMSTG02_Site_beta.teammentor.net\TM40\TM
_4_0_GraphDB\node_modules\levelgraph\lib\getdb.js:27:18)
  at Module._compile (module.js:460:26)
  at Object.Module._extensions..js (module.js:478:10)
  at Module.load (c:\TEAM Mentor\TMSTG02_Site_beta.teammentor.net\TM40\TM_4_0_Gr
aphDB\node_modules\coffee-script\lib\coffee-script\register.js:45:36)
  at Function.Module._load (module.js:310:12)
  at Module.require (module.js:365:17)
  at require (module.js:384:17)
  at levelgraph (c:\TEAM Mentor\TMSTG02_Site_beta.teammentor.net\TM40\TM_4_0_Gra
phDB\node_modules\levelgraph\lib\levelgraph.js:70:20)
  at c:\TEAM Mentor\TMSTG02_Site_beta.teammentor.net\TM40\TM_4_0_GraphDB\src\ser
vices\graph\Graph-Service.coffee:29:15
  at process._tickCallback (node.js:355:11)


npm ERR! Windows_NT 6.3.9600
npm ERR! argv "c:\\Program Files\\nodejs\\node.exe" "c:\\Program Files\\nodejs\\
node_modules\\npm\\bin\\npm-cli.js" "start"
npm ERR! node v0.12.2
npm ERR! npm  v2.7.4
npm ERR! code ELIFECYCLE
npm ERR! TM_4_0_GraphDB@0.0.1 start: `node index.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the TM_4_0_GraphDB@0.0.1 start script 'node index.js'.
npm ERR! This is most likely a problem with the TM_4_0_GraphDB package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node index.js
npm ERR! You can get their info via:
npm ERR!     npm owner ls TM_4_0_GraphDB
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     c:\TEAM Mentor\TMSTG02_Site_beta.teammentor.net\TM40\TM_4_0_GraphDB
\npm-debug.log

Administrator@WIN-P3L0145SVLV /c/TEAM Mentor/TMSTG02_Site_beta.teammentor.net/TM
40/TM_4_0_GraphDB (master)
```

**Comment by roman87** [comment]
However, going directly through swagger and searching for XSS or doing http://localhost:1332/data/articles
works fine.

Seems like the issue is with convert/to_ids

**Comment by roman87** [comment]
The compiler box and the new box both have the same version of node. and npm.
![selection_188](https://cloud.githubusercontent.com/assets/1326120/7437064/0fa251c2-f022-11e4-8b2a-2e16286d64f2.png)

**Comment by DinisCruz** [comment]
The problem is with leveldown  ```
node_modules
\levelgraph\node_modules\leveldown\node_modules\bindings\bindings.js:83```

This looks like that 32bit vs 64bit prob you were talking about with Michael on Slack

Did you guys confirm that the build server matches this server?

**Comment by roman87** [comment]
Yes, this was an issue between compiling on 32 bit and running on 64. The compiler box had 2 versions of node. Old one that was 64 bit and new one that for some reason was 32. I fixed the versions, recompiled and it is running fine on the new box - tmstg02.teammentor.net. I moved beta.teammentor.net to point there.

**Comment by roman87** [comment]
Btw, to find which version of node you are running do:
```
node
process
```

**Comment by michaelhidalgo** [comment]
Thanks for sorting this out! It is great we found the root cause !

2015-05-03 15:10 GMT-06:00 RomichG <notifications@github.com>:

> Btw, to find which version of node you are running do:
>
> node
> process
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/TeamMentor/TM_4_0_Design/issues/740#issuecomment-98544618>
> .
>



-- 
Michael Hidalgo
http://michaelhidalgocr.blogspot.com

*The future has many names: For the weak, it means the unattainable. For
the fearful, it means the unknown. For the courageous, it means
opportunity. (1802-1885) French Poet, Dramatist, Writer*
