### ISSUE TITLE
Crashing DB when searching for "Encryption Keys are stored using protected storrage"

### ISSUE THREAD

**Issue by roman87** [TeamMentor/TM_4_0_Design#793]
```
2015-05-13T05:07:48.243Z - info:  method=GET, url=/search/query_from_text_search/Encryption%20Keys%20are%20stored%20using%20protected%20storrage
2015-05-13T05:07:48.243Z - info: [ensure_TM_Uno_Is_Loaded] Using path_To_Lib_Uno_Json: /home/rom/Dev/TeamMentor/TM_4_0_GraphDB/.tmCache/Lib_UNO-json/Graph_Data
/home/rom/Dev/TeamMentor/TM_4_0_GraphDB/src/services/text-search/Search-Text-Service.coffee:152
                  if (tag_Articles.contains(result.id)) {
                                   ^
TypeError: undefined is not a function
  at add_Tag_Mappings (/home/rom/Dev/TeamMentor/TM_4_0_GraphDB/src/services/text-search/Search-Text-Service.coffee:95:31)
  at /home/rom/Dev/TeamMentor/TM_4_0_GraphDB/src/services/text-search/Search-Text-Service.coffee:105:9
  at Search_Text_Service.search_Mappings (/home/rom/Dev/TeamMentor/TM_4_0_GraphDB/src/services/text-search/Search-Text-Service.coffee:26:14)
  at Search_Text_Service.search_Mappings (/home/rom/Dev/TeamMentor/TM_4_0_GraphDB/src/services/text-search/Search-Text-Service.coffee:1:1)
  at /home/rom/Dev/TeamMentor/TM_4_0_GraphDB/src/services/text-search/Search-Text-Service.coffee:64:9
  at Search_Text_Service.tag_Mappings (/home/rom/Dev/TeamMentor/TM_4_0_GraphDB/src/services/text-search/Search-Text-Service.coffee:37:14)
  at Search_Text_Service.tag_Mappings (/home/rom/Dev/TeamMentor/TM_4_0_GraphDB/src/services/text-search/Search-Text-Service.coffee:1:1)
  at Search_Text_Service.word_Score (/home/rom/Dev/TeamMentor/TM_4_0_GraphDB/src/services/text-search/Search-Text-Service.coffee:63:7)
  at Search_Text_Service.word_Score (/home/rom/Dev/TeamMentor/TM_4_0_GraphDB/src/services/text-search/Search-Text-Service.coffee:1:1)
  at get_Score (/home/rom/Dev/TeamMentor/TM_4_0_GraphDB/src/services/text-search/Search-Text-Service.coffee:122:10)
  at iterate (/home/rom/Dev/TeamMentor/TM_4_0_GraphDB/node_modules/async/lib/async.js:149:13)
  at /home/rom/Dev/TeamMentor/TM_4_0_GraphDB/node_modules/async/lib/async.js:160:25
  at /home/rom/Dev/TeamMentor/TM_4_0_GraphDB/src/services/text-search/Search-Text-Service.coffee:124:11
  at /home/rom/Dev/TeamMentor/TM_4_0_GraphDB/src/services/text-search/Search-Text-Service.coffee:109:9
  at Search_Text_Service.search_Mappings (/home/rom/Dev/TeamMentor/TM_4_0_GraphDB/src/services/text-search/Search-Text-Service.coffee:26:14)
  at Search_Text_Service.search_Mappings (/home/rom/Dev/TeamMentor/TM_4_0_GraphDB/src/services/text-search/Search-Text-Service.coffee:1:1)
  at /home/rom/Dev/TeamMentor/TM_4_0_GraphDB/src/services/text-search/Search-Text-Service.coffee:64:9
  at Search_Text_Service.tag_Mappings (/home/rom/Dev/TeamMentor/TM_4_0_GraphDB/src/services/text-search/Search-Text-Service.coffee:43:16)
  at Search_Text_Service.tag_Mappings (/home/rom/Dev/TeamMentor/TM_4_0_GraphDB/src/services/text-search/Search-Text-Service.coffee:1:1)
  at Search_Text_Service.word_Score (/home/rom/Dev/TeamMentor/TM_4_0_GraphDB/src/services/text-search/Search-Text-Service.coffee:63:7)
  at Search_Text_Service.word_Score (/home/rom/Dev/TeamMentor/TM_4_0_GraphDB/src/services/text-search/Search-Text-Service.coffee:1:1)
  at get_Score (/home/rom/Dev/TeamMentor/TM_4_0_GraphDB/src/services/text-search/Search-Text-Service.coffee:122:10)
  at iterate (/home/rom/Dev/TeamMentor/TM_4_0_GraphDB/node_modules/async/lib/async.js:149:13)
  at Object.async.eachSeries (/home/rom/Dev/TeamMentor/TM_4_0_GraphDB/node_modules/async/lib/async.js:165:9)
  at /home/rom/Dev/TeamMentor/TM_4_0_GraphDB/src/services/text-search/Search-Text-Service.coffee:126:13
  at /home/rom/Dev/TeamMentor/TM_4_0_GraphDB/src/services/text-search/Search-Text-Service.coffee:109:9
  at Search_Text_Service.search_Mappings (/home/rom/Dev/TeamMentor/TM_4_0_GraphDB/src/services/text-search/Search-Text-Service.coffee:32:14)
  at Search_Text_Service.search_Mappings (/home/rom/Dev/TeamMentor/TM_4_0_GraphDB/src/services/text-search/Search-Text-Service.coffee:1:1)
  at /home/rom/Dev/TeamMentor/TM_4_0_GraphDB/src/services/text-search/Search-Text-Service.coffee:64:9
  at /home/rom/Dev/TeamMentor/TM_4_0_GraphDB/src/services/text-search/Search-Text-Service.coffee:45:7
  at /home/rom/Dev/TeamMentor/TM_4_0_GraphDB/src/services/text-search/Search-Artifacts-Service.coffee:34:7
  at /home/rom/Dev/TeamMentor/TM_4_0_GraphDB/src/services/graph/Graph-Find.coffee:227:7
  at /home/rom/Dev/TeamMentor/TM_4_0_GraphDB/src/services/graph/Graph-Service.coffee:197:76
  at CallbackStream.<anonymous> (/home/rom/Dev/TeamMentor/TM_4_0_GraphDB/node_modules/levelgraph/node_modules/callback-stream/index.js:23:5)
  at CallbackStream.emit (events.js:129:20)
  at finishMaybe (_stream_writable.js:484:14)
  at endWritable (_stream_writable.js:493:3)
  at CallbackStream.Writable.end (_stream_writable.js:459:5)
  at ReadStream.onend (/home/rom/Dev/TeamMentor/TM_4_0_GraphDB/node_modules/levelgraph/node_modules/readable-stream/lib/_stream_readable.js:523:10)
  at ReadStream.g (events.js:199:16)
  at ReadStream.emit (events.js:104:17)
  at /home/rom/Dev/TeamMentor/TM_4_0_GraphDB/node_modules/levelgraph/node_modules/readable-stream/lib/_stream_readable.js:965:16
  at process._tickCallback (node.js:355:11)


npm ERR! Linux 3.16-0.bpo.2-amd64
npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "start"
npm ERR! node v0.12.2
npm ERR! npm  v2.7.4
npm ERR! code ELIFECYCLE
npm ERR! TM_4_0_GraphDB@0.0.1 start: `node index.js`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the TM_4_0_GraphDB@0.0.1 start script 'node index.js'.
npm ERR! This is most likely a problem with the TM_4_0_GraphDB package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node index.js
npm ERR! You can get their info via:
npm ERR!     npm owner ls TM_4_0_GraphDB
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /home/rom/Dev/TeamMentor/TM_4_0_GraphDB/npm-debug.log
```

**Comment by roman87** [comment]
And connection gets reset when searching for "keys"

![selection_237](https://cloud.githubusercontent.com/assets/1326120/7604228/1fd8f192-f90d-11e4-8b7b-fc15fbaa6a83.png)

**Comment by DinisCruz** [comment]
Good catch, just fixed it

![image](https://cloud.githubusercontent.com/assets/656739/7609714/e321baf2-f96d-11e4-825f-5c2a1172faa0.png)

@tekgirl77 can you add a unit test to regress test this (since it has been fixed)

**Comment by DinisCruz** [comment]
![image](https://cloud.githubusercontent.com/assets/656739/7609724/fe2ad59a-f96d-11e4-851b-adde0b167258.png)

**Comment by roman87** [comment]
All fixed. good stuff.
