### ISSUE TITLE
Unable to start Dev branch in Windows

### ISSUE THREAD

**Issue by romichg** [TeamMentor/TM_4_0_Design#878]
Looks like some path related issue

40/TM/code/TM_GraphDB ((c119139...))
$ npm start

> TM_4_0_GraphDB@0.0.1 start c:\TeamMentor\TMDEVR01-Site_beta.teammentor.net\TM4
> 0\TM\code\TM_GraphDB
> npm run start-nodemon
> 
> TM_4_0_GraphDB@0.0.1 start-nodemon c:\TeamMentor\TMDEVR01-Site_beta.teammentor
> .net\TM40\TM\code\TM_GraphDB
> node ./node_modules/.bin/nodemon --watch src -e coffee app.js

c:\TeamMentor\TMDEVR01-Site_beta.teammentor.net\TM40\TM\code\TM_GraphDB\node_mod
ules.bin\nodemon:2
basedir=`dirname "$0"`
        ^
SyntaxError: Unexpected token ILLEGAL
    at exports.runInThisContext (vm.js:73:16)
    at Module._compile (module.js:443:25)
    at Object.Module._extensions..js (module.js:478:10)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Function.Module.runMain (module.js:501:10)
    at startup (node.js:129:16)
    at node.js:814:3

npm ERR! Windows_NT 6.3.9600
npm ERR! argv "c:\Program Files\nodejs\\node.exe" "c:\Program Files\nodejs

**Comment by romichg** [comment]
This is fixed
