### ISSUE TITLE
Reload breaks on latest Lib_Uno changes

### ISSUE THREAD

**Issue by romichg** [TeamMentor/TM_4_0_Design#881]
```
rom@TITI08:~/Dev/TeamMentor/TM$ git submodule 
 00be9cd41f5d101f0d9b57828e829b5e505022e4 build/TM_4_0_JSON_Data (heads/master)
 98d40d5b8c5748cab0afa0d147cc57a2de326ae3 build/TM_Gulp (98d40d5)
 d8a0d06372f84bc934685eb4a6b41912079145e5 code/TM_Flare (remotes/origin/Dev)
 c1191396c5e77ee50e9f5732795eabcfed9c26a5 code/TM_GraphDB (4.0.1-7-gc119139)
 5f11fac01ef4b011bf45211d1a73866e6e809fd3 code/TM_Jade (remotes/origin/Issue_618_Flare_Wired)
 eb5d7e361ac72cdaee514c3e49922e9d29a1b13d code/TM_Shared (heads/master)
 43745756fc01e601c14fa405644ba1aa8fe4fd4e code/TM_Static (4374575)
 12ba3a1d16ce0c7f90eedf9a4679add156dbcddf code/TM_Website (remotes/origin/Dev)
 5a2fe18c6924b2ee2d8777750acb3207742f76ea config/SiteData_TM (remotes/origin/Dev)
 5286dbd12f0e6118db3946980d2fae8056343b56 data/Lib_Docs-json (heads/master)
 a5b5b52b635eb90f65ffa7aa049db0aa5ef30c7f data/Lib_UNO (remotes/origin/Beta)
 c10d4b6bc634f151820e2264ca98eee46b57fa28 data/Lib_UNO-json (heads/master)
 3de09563c7a1085085e19c8979653baef23ee032 qa/TM_QA (4.0.1-16-g3de0956)
rom@TITI08:~/Dev/TeamMentor/TM$ ./bin/reload_data.sh

---- reloading tm graph from Lib_Uno data ----

[step 1] convert Xml files into Json
[convert_Xml_File] converting xml file into json: /Articles/0c11e362-82d1-4132-ba66-8431eb02da94.xml
[convert_Xml_File] converting xml file into json: /Articles/0e774522-7d2e-4a14-b3cf-850d127c3895.xml
[convert_Xml_File] converting xml file into json: /Articles/10886993-6dcd-4905-b577-2032edd530c5.xml
[convert_Xml_File] converting xml file into json: /Articles/13ad7fa3-199e-4957-9e4f-39bd931c9f1d.xml
[convert_Xml_File] converting xml file into json: /Articles/189c97b5-78ac-4b3b-812d-587ea2a895e4.xml
[convert_Xml_File] converting xml file into json: /Articles/24771ceb-219a-41c5-8877-c040969a6933.xml
[convert_Xml_File] converting xml file into json: /Articles/27bea6b1-776b-46d4-8e9e-f74df6341be0.xml
[convert_Xml_File] converting xml file into json: /Articles/353bbdfb-3d1e-494f-978c-e581f128ed4a.xml
[convert_Xml_File] converting xml file into json: /Articles/3b306aa2-2aaa-4b58-9f0a-08beb5a3cafa.xml
[convert_Xml_File] converting xml file into json: /Articles/41a04d3f-0bb5-4904-bb28-134a109f9ce0.xml
[convert_Xml_File] converting xml file into json: /Articles/42ff8254-15b9-4e5c-af6e-0ea617354b4f.xml
[convert_Xml_File] converting xml file into json: /Articles/4a62104f-8abf-4d1f-8959-04b59b6db3b4.xml
[convert_Xml_File] converting xml file into json: /Articles/52624de3-7c13-4456-974b-23c4588eef0d.xml
[convert_Xml_File] converting xml file into json: /Articles/5de9c87b-5678-4810-8636-65b720e023bf.xml
[convert_Xml_File] converting xml file into json: /Articles/60459daa-5678-45f7-834f-72ef487aaf2b.xml
[convert_Xml_File] converting xml file into json: /Articles/6ae55d03-3aac-45c2-8516-140b60ee501e.xml
[convert_Xml_File] converting xml file into json: /Articles/7718e002-fad0-4114-b51f-f46397cd3921.xml
[convert_Xml_File] converting xml file into json: /Articles/8a5cb8a0-d7f9-4372-bae6-2d680bb498ad.xml
[convert_Xml_File] converting xml file into json: /Articles/8e2cab7b-bab6-488d-9487-d93b3f479b27.xml
[convert_Xml_File] converting xml file into json: /Articles/93b69439-8607-4b3b-af6a-70afa775afd3.xml
[convert_Xml_File] converting xml file into json: /Articles/b26ece13-3df3-4cd5-bf76-fbded344ebb1.xml
[convert_Xml_File] converting xml file into json: /Articles/d4d55f1d-9e76-4f8d-85a5-eabae93213c8.xml
[convert_Xml_File] converting xml file into json: /Articles/ec353b5b-901b-404b-811e-922561c1e632.xml
TypeError: Cannot read property 'checksum' of null
  at /home/rom/Dev/TeamMentor/TM/build/TM_4_0_JSON_Data/src/services/Content-Service.coffee:50:27
  at /home/rom/Dev/TeamMentor/TM/build/TM_4_0_JSON_Data/node_modules/async/lib/async.js:122:13
  at _each (/home/rom/Dev/TeamMentor/TM/build/TM_4_0_JSON_Data/node_modules/async/lib/async.js:46:13)
  at Object.async.each (/home/rom/Dev/TeamMentor/TM/build/TM_4_0_JSON_Data/node_modules/async/lib/async.js:121:9)
  at Content_Service.convert_Xml_To_Json (/home/rom/Dev/TeamMentor/TM/build/TM_4_0_JSON_Data/src/services/Content-Service.coffee:67:11)
  at Content_Service.convert_Xml_To_Json (/home/rom/Dev/TeamMentor/TM/build/TM_4_0_JSON_Data/src/services/Content-Service.coffee:1:1)
  at step_1 (/home/rom/Dev/TeamMentor/TM/build/TM_4_0_JSON_Data/src/tool-update-mappings.coffee:23:19)
  at Object.<anonymous> (/home/rom/Dev/TeamMentor/TM/build/TM_4_0_JSON_Data/src/tool-update-mappings.coffee:45:1)
  at Object.<anonymous> (/home/rom/Dev/TeamMentor/TM/build/TM_4_0_JSON_Data/src/tool-update-mappings.coffee:3:1)
  at Module._compile (module.js:460:26)
  at Object.exports.run (/usr/local/lib/node_modules/coffee-script/lib/coffee-script/coffee-script.js:119:23)
  at compileScript (/usr/local/lib/node_modules/coffee-script/lib/coffee-script/command.js:208:29)
  at compilePath (/usr/local/lib/node_modules/coffee-script/lib/coffee-script/command.js:161:14)
  at Object.exports.run (/usr/local/lib/node_modules/coffee-script/lib/coffee-script/command.js:96:21)
  at Object.<anonymous> (/usr/local/lib/node_modules/coffee-script/bin/coffee:7:41)
  at Module._compile (module.js:460:26)
  at Object.Module._extensions..js (module.js:478:10)
  at Module.load (module.js:355:32)
  at Function.Module._load (module.js:310:12)
  at Function.Module.runMain (module.js:501:10)
  at startup (node.js:129:16)
  at node.js:814:3
```

**Comment by romichg** [comment]
Btw, nuking the subfolders inside Lib_UNO-json and running reload works fine and reloads the whole thing

**Comment by DinisCruz** [comment]
This bug is happening here: https://github.com/TeamMentor/TM_4_0_JSON_Data/blob/master/src/services/Content-Service.coffee#L48-L50

``` coffee
      json_File.parent_Folder().folder_Create()
      contents  = xml_File.file_Contents()
      checksum  = contents.checksum()
```

which should only happen if the xml_File file is empty, which thinking about it should only happen if the file has been deleted

**Comment by romichg** [comment]
What happens if there are new files? There were a few files deleted though. How do we handle it so we don't crash?

**Comment by DinisCruz** [comment]
New files are handled ok since the file will exist and it will be processed since the checksum will not match

I'm writing a fix for the case you hit above

**Comment by DinisCruz** [comment]
Here is the test that replicates the prob

``` coffee
describe.only 'Regression Tests', ->
  it 'Issue 881 - Reload breaks on latest Lib_Uno changes', (done)->
    using new Content_Service(), ->
      @.map_Source_Files = ()->
        '0010a1e4-6d8f-41a4-8eaf-000011112222':
            xml_File:  '/Articles/AAAAAA.xml'
            json_File: '/Articles/AAAAAA.json'
            data_File: '/00/AAAAAA.json'
            checksum:  '6ea8d761237952a1b13fac0000000000'
            xml_Size:  4242

      log @.folder_Library()
      log @.map_Source_Files()
      @.convert_Xml_To_Json ->

        log 'done'
        done()
```

![image](https://cloud.githubusercontent.com/assets/656739/8397591/6c7bc156-1dc9-11e5-8578-f42f1b9658e8.png)

**Comment by DinisCruz** [comment]
The fix is don by adding this inside the `convert_Xml_To_Json` method

``` coffee
      return next() if xml_File.file_Not_Exists()
```

Here is the regression test

``` coffee
describe.only 'Regression Tests', ->
  it 'Issue 881 - Reload breaks on latest Lib_Uno changes', (done)->
    using new Content_Service(), ->
      @.map_Source_Files = ()->
        '0010a1e4-6d8f-41a4-8eaf-000011112222':
            xml_File:  '/Articles/AAAAAA.xml'                   # issue happened when xml_File did not exist
      @.convert_Xml_To_Json done
```

**Comment by DinisCruz** [comment]
@roman87 can you double check that new files are picked up without needing to delete the Mappings folder (inside Lib_UNO-json), there might be an issue with that workflow

**Comment by romichg** [comment]
This is now fixed. However: https://github.com/TeamMentor/TM_4_0_Design/issues/888
